# Generated by Django 4.2.7 on 2026-05-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('sequence_number', models.PositiveIntegerField(default=0, editable=False)),
                ('sequence_year', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('sequence_month', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_deleted', 'is_active'], name='products_pr_is_dele_88b8a2_idx'), models.Index(fields=['sequence_year', 'sequence_month', 'sequence_number'], name='products_pr_sequenc_224f15_idx')],
            },
        ),
    ]
