# Generated by Django 4.2.7 on 2026-05-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('color', 'Color')], db_index=True, default='text', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.CharField(db_index=True, max_length=100)),
                ('color_code', models.CharField(blank=True, help_text='Optional hex like #FF0000.', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attributes/values/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['attribute', 'sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['variant', 'attribute', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='signature',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'signature'), name='products_unique_variant_signature'),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_links', to='products.attribute'),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_links', to='products.attributevalue'),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='products.attribute'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['is_deleted', 'is_active', 'sort_order'], name='products_at_is_dele_1e114b_idx'),
        ),
        migrations.AddConstraint(
            model_name='variantattribute',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute'), name='products_unique_variant_attribute'),
        ),
        migrations.AddConstraint(
            model_name='variantattribute',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute_value'), name='products_unique_variant_attribute_value'),
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['attribute', 'is_active', 'sort_order'], name='products_at_attribu_2680b7_idx'),
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['attribute', 'value'], name='products_at_attribu_599472_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
    ]
