# Generated by Django 4.2.7 on 2026-05-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_attribute_attributevalue_variantattribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('keyword', models.CharField(max_length=255)),
                ('normalized_keyword', models.CharField(db_index=True, max_length=255, unique=True)),
                ('search_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('last_searched_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-search_count', '-last_searched_at'],
                'indexes': [models.Index(fields=['-search_count', '-last_searched_at'], name='products_pr_search__7d8535_idx')],
            },
        ),
    ]
