# Generated by Django 4.2.7 on 2026-05-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', 'created_at'], name='orders_orde_payment_e2cb15_idx'),
        ),
    ]
