# Generated by Django 4.2.7 on 2026-05-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mobile_number",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]

