# Generated by Django 6.0.2 on 2026-05-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_discount_amount_order_shipping_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="note",
            new_name="delivery_address",
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(),
        ),
    ]

