# Generated by Django 4.2.7 on 2026-05-01 04:37

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('sequence_number', models.PositiveIntegerField(default=0, editable=False)),
                ('sequence_year', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('sequence_month', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('sequence_number', models.PositiveIntegerField(default=0, editable=False)),
                ('sequence_year', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('sequence_month', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incomes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='orders.order')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('entry_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='accounts.expense')),
                ('income', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='accounts.income')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['entry_type', 'date'], name='accounts_le_entry_t_b7818f_idx'), models.Index(fields=['date', 'amount'], name='accounts_le_date_92c2cf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['sequence_year', 'sequence_month', 'sequence_number'], name='accounts_in_sequenc_06194f_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['date', 'amount'], name='accounts_in_date_5f17a1_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['sequence_year', 'sequence_month', 'sequence_number'], name='accounts_ex_sequenc_38a522_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date', 'amount'], name='accounts_ex_date_6a7776_idx'),
        ),
    ]
