from __future__ import annotations

"""
Custom URL path converters.

We use these to avoid greedy `<path:...>` converters when public IDs contain `/`.
Example Product public_id: `PRD-1/05-26`

Using a restricted converter prevents URL routing conflicts such as:
  /products/PRD-1/05-26/variants/10/delete/
being incorrectly matched by:
  /products/<path:public_id>/delete/
"""


class ProductPublicIdConverter:
    """
    Matches Product.public_id values generated by `core.utils.id_generator.build_monthly_public_id`
    for Product prefix "PRD", e.g. PRD-1/05-26
    """

    regex = r"PRD-\d+/\d{2}-\d{2}"

    def to_python(self, value: str) -> str:
        return value

    def to_url(self, value: str) -> str:
        return value

