# Generated by Django 4.2.7 on 2026-05-06 00:00

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0005_attribute_attributevalue_variantattribute_and_more"),
        ("orders", "0004_order_mobile_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(choices=[("percent", "Percentage"), ("fixed", "Fixed amount"), ("bxgy", "Buy X Get Y"), ("free_shipping", "Free shipping")], db_index=True, max_length=30),
                ),
                ("percent_off", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=6)),
                ("amount_off", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("bxgy_buy_qty", models.PositiveIntegerField(default=0)),
                ("bxgy_get_qty", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("auto_apply", models.BooleanField(db_index=True, default=False)),
                ("starts_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("min_order_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("one_time_per_user", models.BooleanField(default=False, help_text="If enabled, each user can redeem once.")),
                ("usage_limit", models.PositiveIntegerField(blank=True, help_text="Optional global usage limit.", null=True)),
                ("times_redeemed", models.PositiveIntegerField(default=0, editable=False)),
                ("allowed_users", models.ManyToManyField(blank=True, related_name="allowed_promo_codes", to=settings.AUTH_USER_MODEL)),
                ("applicable_categories", models.ManyToManyField(blank=True, related_name="promo_codes", to="products.category")),
                ("applicable_products", models.ManyToManyField(blank=True, related_name="promo_codes", to="products.product")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoRedemption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("subtotal_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("shipping_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("applied_via_auto", models.BooleanField(default=False)),
                ("order", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="promo_redemption", to="orders.order")),
                ("promo_code", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="redemptions", to="coupons.promocode")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="promo_redemptions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]

