# Generated by Django 4.2.7 on 2026-05-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount_type_product_discount_value_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('last_counted_at', models.DateTimeField(blank=True, null=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item', to='products.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['quantity_on_hand'], name='inventory_v_quantit_939878_idx')],
            },
        ),
    ]
