# Generated by Django 4.2.7 on 2026-05-01 06:09

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tracking_url_template', models.CharField(blank=True, help_text='Optional template, e.g. https://courier.example/track/{tracking_number}', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('countries', models.TextField(blank=True, help_text='Comma-separated country codes (e.g., BD,IN).')),
                ('regions', models.TextField(blank=True, help_text='Comma-separated regions/cities.')),
                ('postal_prefixes', models.TextField(blank=True, help_text='Comma-separated postal code prefixes.')),
                ('fixed_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('per_item_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('free_shipping_min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shipped_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping.courier')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders.order')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping.deliveryzone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.TextField(blank=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='shipping.shipment')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['is_active', 'name'], name='shipping_de_is_acti_f6cff7_idx'),
        ),
        migrations.AddIndex(
            model_name='courier',
            index=models.Index(fields=['is_active', 'name'], name='shipping_co_is_acti_466f48_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttrackingevent',
            index=models.Index(fields=['shipment', 'timestamp'], name='shipping_sh_shipmen_c39492_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'created_at'], name='shipping_sh_status_58d901_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipping_sh_trackin_af3d4f_idx'),
        ),
    ]
